pipeline {
    agent any
    stages {
        stage('Maven') {
            steps {
               sh '''
               export MAVEN_HOME=/opt/maven
               export PATH=$PATH:$MAVEN_HOME/bin
               mvn --version
               mvn clean package
               '''
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
